export const LAYOUT_CONSTANTS = {
  SIDE_PANEL_WRAPPER_ID: 'admin-side-panel-wrapper',
  SIDE_PANEL_MIN_WIDTH: 420,
  SIDE_PANEL_DEFAULT_WIDTH: 520,
  SIDE_PANEL_MAX_WIDTH: 800,
  RESPONSIVE_OVERLAY_BREAKPOINT: 1024,
} as const;
